import { Manager } from './manage';
export declare function generatorApi(configFile: string): Promise<Manager>;
export declare function isUrl(str: string): boolean;
export declare function getTemplate(templatePath: string, required?: boolean): any;
export declare function toDashCase(str: string): string;
export declare function toUpperFirstLetter(text: string): string;
export declare function getMaxSamePath(paths: string[], samePath?: string): string;
export declare function getIdentifierFromUrl(url: string, requestType: string, samePath?: string): string;
export declare function getIdentifierFromOperatorId(operationId: string): string;
export declare function reviseModName(modName: string): string;
export declare function hasChinese(str: string): RegExpMatchArray;
export declare function jsonStingTransformObject(jsStr: any): any;
export declare function transformCamelCase(name: string): string;
export declare function getFileName(fileName: string, surrounding: string): string;
export declare function format(fileContent: string, prettierOpts: Record<string, string>): any;
